
# This file is automatically generated, you probably don't want to edit this

jamovipdiffpairedOptions <- if (requireNamespace("jmvcore", quietly=TRUE)) R6::R6Class(
    "jamovipdiffpairedOptions",
    inherit = jmvcore::Options,
    public = list(
        initialize = function(
            switch = "from_raw",
            reference_measure = NULL,
            comparison_measure = NULL,
            cases_consistent = " ",
            cases_inconsistent = " ",
            not_cases_consistent = " ",
            not_cases_inconsistent = " ",
            case_label = "Sick",
            not_case_label = "Well",
            comparison_measure_name = "Post-test",
            reference_measure_name = "Pre-test",
            conf_level = 95,
            show_details = FALSE,
            evaluate_hypotheses = FALSE,
            null_value = "0",
            null_boundary = "0",
            alpha = 0.05,
            null_color = "#A40122",
            es_plot_width = "400",
            es_plot_height = "450",
            ymin = "auto",
            ymax = "auto",
            ybreaks = "auto",
            ylab = "auto",
            xlab = "auto",
            axis.text.y = "14",
            axis.title.y = "15",
            axis.text.x = "14",
            axis.title.x = "15",
            simple_contrast_labels = TRUE,
            error_layout = "none",
            difference_axis_breaks = "auto",
            shape_summary_reference = "circle filled",
            shape_summary_comparison = "circle filled",
            shape_summary_difference = "triangle filled",
            color_summary_reference = "#008DF9",
            color_summary_comparison = "#009F81",
            color_summary_difference = "black",
            fill_summary_reference = "#008DF9",
            fill_summary_comparison = "#009F81",
            fill_summary_difference = "black",
            size_summary_reference = "4",
            size_summary_comparison = "4",
            size_summary_difference = "4",
            alpha_summary_reference = "1",
            alpha_summary_comparison = "1",
            alpha_summary_difference = "1",
            linetype_summary_reference = "solid",
            linetype_summary_comparison = "solid",
            linetype_summary_difference = "solid", ...) {

            super$initialize(
                package="esci",
                name="jamovipdiffpaired",
                requiresData=TRUE,
                ...)

            private$..switch <- jmvcore::OptionList$new(
                "switch",
                switch,
                default="from_raw",
                options=list(
                    "from_raw",
                    "from_summary"))
            private$..reference_measure <- jmvcore::OptionVariable$new(
                "reference_measure",
                reference_measure,
                suggested=list(
                    "nominal",
                    "ordinal"),
                permitted=list(
                    "factor"))
            private$..comparison_measure <- jmvcore::OptionVariable$new(
                "comparison_measure",
                comparison_measure,
                suggested=list(
                    "nominal",
                    "ordinal"),
                permitted=list(
                    "factor"))
            private$..cases_consistent <- jmvcore::OptionString$new(
                "cases_consistent",
                cases_consistent,
                default=" ")
            private$..cases_inconsistent <- jmvcore::OptionString$new(
                "cases_inconsistent",
                cases_inconsistent,
                default=" ")
            private$..not_cases_consistent <- jmvcore::OptionString$new(
                "not_cases_consistent",
                not_cases_consistent,
                default=" ")
            private$..not_cases_inconsistent <- jmvcore::OptionString$new(
                "not_cases_inconsistent",
                not_cases_inconsistent,
                default=" ")
            private$..case_label <- jmvcore::OptionString$new(
                "case_label",
                case_label,
                default="Sick")
            private$..not_case_label <- jmvcore::OptionString$new(
                "not_case_label",
                not_case_label,
                default="Well")
            private$..comparison_measure_name <- jmvcore::OptionString$new(
                "comparison_measure_name",
                comparison_measure_name,
                default="Post-test")
            private$..reference_measure_name <- jmvcore::OptionString$new(
                "reference_measure_name",
                reference_measure_name,
                default="Pre-test")
            private$..conf_level <- jmvcore::OptionNumber$new(
                "conf_level",
                conf_level,
                default=95)
            private$..show_details <- jmvcore::OptionBool$new(
                "show_details",
                show_details,
                default=FALSE)
            private$..evaluate_hypotheses <- jmvcore::OptionBool$new(
                "evaluate_hypotheses",
                evaluate_hypotheses,
                default=FALSE)
            private$..null_value <- jmvcore::OptionString$new(
                "null_value",
                null_value,
                default="0")
            private$..null_boundary <- jmvcore::OptionString$new(
                "null_boundary",
                null_boundary,
                default="0")
            private$..alpha <- jmvcore::OptionNumber$new(
                "alpha",
                alpha,
                default=0.05)
            private$..null_color <- jmvcore::OptionList$new(
                "null_color",
                null_color,
                default="#A40122",
                options=list(
                    "black",
                    "#00C2F9",
                    "#008DF9",
                    "#009F81",
                    "#FF5AAF",
                    "#9F0162",
                    "#A40122",
                    "#00FCCF",
                    "#FF6E3A",
                    "#FFB2FD",
                    "#8400CD",
                    "#E20134",
                    "#FFC33B",
                    "white",
                    "NA",
                    "NA",
                    "gray0",
                    "gray5",
                    "gray10",
                    "gray15",
                    "gray20",
                    "gray25",
                    "gray30",
                    "gray35",
                    "gray40",
                    "gray45",
                    "gray50",
                    "gray55",
                    "gray60",
                    "gray65",
                    "gray70",
                    "gray75",
                    "gray80",
                    "gray85",
                    "gray90",
                    "gray95",
                    "gray100"))
            private$..es_plot_width <- jmvcore::OptionString$new(
                "es_plot_width",
                es_plot_width,
                default="400")
            private$..es_plot_height <- jmvcore::OptionString$new(
                "es_plot_height",
                es_plot_height,
                default="450")
            private$..ymin <- jmvcore::OptionString$new(
                "ymin",
                ymin,
                default="auto")
            private$..ymax <- jmvcore::OptionString$new(
                "ymax",
                ymax,
                default="auto")
            private$..ybreaks <- jmvcore::OptionString$new(
                "ybreaks",
                ybreaks,
                default="auto")
            private$..ylab <- jmvcore::OptionString$new(
                "ylab",
                ylab,
                default="auto")
            private$..xlab <- jmvcore::OptionString$new(
                "xlab",
                xlab,
                default="auto")
            private$..axis.text.y <- jmvcore::OptionString$new(
                "axis.text.y",
                axis.text.y,
                default="14")
            private$..axis.title.y <- jmvcore::OptionString$new(
                "axis.title.y",
                axis.title.y,
                default="15")
            private$..axis.text.x <- jmvcore::OptionString$new(
                "axis.text.x",
                axis.text.x,
                default="14")
            private$..axis.title.x <- jmvcore::OptionString$new(
                "axis.title.x",
                axis.title.x,
                default="15")
            private$..simple_contrast_labels <- jmvcore::OptionBool$new(
                "simple_contrast_labels",
                simple_contrast_labels,
                default=TRUE)
            private$..error_layout <- jmvcore::OptionList$new(
                "error_layout",
                error_layout,
                default="none",
                options=list(
                    "none"))
            private$..difference_axis_breaks <- jmvcore::OptionString$new(
                "difference_axis_breaks",
                difference_axis_breaks,
                default="auto")
            private$..shape_summary_reference <- jmvcore::OptionList$new(
                "shape_summary_reference",
                shape_summary_reference,
                default="circle filled",
                options=list(
                    "circle filled",
                    "square filled",
                    "triangle filled",
                    "diamond filled"))
            private$..shape_summary_comparison <- jmvcore::OptionList$new(
                "shape_summary_comparison",
                shape_summary_comparison,
                default="circle filled",
                options=list(
                    "circle filled",
                    "square filled",
                    "triangle filled",
                    "diamond filled"))
            private$..shape_summary_difference <- jmvcore::OptionList$new(
                "shape_summary_difference",
                shape_summary_difference,
                default="triangle filled",
                options=list(
                    "circle filled",
                    "square filled",
                    "triangle filled",
                    "diamond filled"))
            private$..color_summary_reference <- jmvcore::OptionList$new(
                "color_summary_reference",
                color_summary_reference,
                default="#008DF9",
                options=list(
                    "black",
                    "#00C2F9",
                    "#008DF9",
                    "#009F81",
                    "#FF5AAF",
                    "#9F0162",
                    "#A40122",
                    "#00FCCF",
                    "#FF6E3A",
                    "#FFB2FD",
                    "#8400CD",
                    "#E20134",
                    "#FFC33B",
                    "white",
                    "NA",
                    "NA",
                    "gray0",
                    "gray5",
                    "gray10",
                    "gray15",
                    "gray20",
                    "gray25",
                    "gray30",
                    "gray35",
                    "gray40",
                    "gray45",
                    "gray50",
                    "gray55",
                    "gray60",
                    "gray65",
                    "gray70",
                    "gray75",
                    "gray80",
                    "gray85",
                    "gray90",
                    "gray95",
                    "gray100"))
            private$..color_summary_comparison <- jmvcore::OptionList$new(
                "color_summary_comparison",
                color_summary_comparison,
                default="#009F81",
                options=list(
                    "black",
                    "#00C2F9",
                    "#008DF9",
                    "#009F81",
                    "#FF5AAF",
                    "#9F0162",
                    "#A40122",
                    "#00FCCF",
                    "#FF6E3A",
                    "#FFB2FD",
                    "#8400CD",
                    "#E20134",
                    "#FFC33B",
                    "white",
                    "NA",
                    "NA",
                    "gray0",
                    "gray5",
                    "gray10",
                    "gray15",
                    "gray20",
                    "gray25",
                    "gray30",
                    "gray35",
                    "gray40",
                    "gray45",
                    "gray50",
                    "gray55",
                    "gray60",
                    "gray65",
                    "gray70",
                    "gray75",
                    "gray80",
                    "gray85",
                    "gray90",
                    "gray95",
                    "gray100"))
            private$..color_summary_difference <- jmvcore::OptionList$new(
                "color_summary_difference",
                color_summary_difference,
                default="black",
                options=list(
                    "black",
                    "#00C2F9",
                    "#008DF9",
                    "#009F81",
                    "#FF5AAF",
                    "#9F0162",
                    "#A40122",
                    "#00FCCF",
                    "#FF6E3A",
                    "#FFB2FD",
                    "#8400CD",
                    "#E20134",
                    "#FFC33B",
                    "white",
                    "NA",
                    "NA",
                    "gray0",
                    "gray5",
                    "gray10",
                    "gray15",
                    "gray20",
                    "gray25",
                    "gray30",
                    "gray35",
                    "gray40",
                    "gray45",
                    "gray50",
                    "gray55",
                    "gray60",
                    "gray65",
                    "gray70",
                    "gray75",
                    "gray80",
                    "gray85",
                    "gray90",
                    "gray95",
                    "gray100"))
            private$..fill_summary_reference <- jmvcore::OptionList$new(
                "fill_summary_reference",
                fill_summary_reference,
                default="#008DF9",
                options=list(
                    "black",
                    "#00C2F9",
                    "#008DF9",
                    "#009F81",
                    "#FF5AAF",
                    "#9F0162",
                    "#A40122",
                    "#00FCCF",
                    "#FF6E3A",
                    "#FFB2FD",
                    "#8400CD",
                    "#E20134",
                    "#FFC33B",
                    "white",
                    "NA",
                    "NA",
                    "gray0",
                    "gray5",
                    "gray10",
                    "gray15",
                    "gray20",
                    "gray25",
                    "gray30",
                    "gray35",
                    "gray40",
                    "gray45",
                    "gray50",
                    "gray55",
                    "gray60",
                    "gray65",
                    "gray70",
                    "gray75",
                    "gray80",
                    "gray85",
                    "gray90",
                    "gray95",
                    "gray100"))
            private$..fill_summary_comparison <- jmvcore::OptionList$new(
                "fill_summary_comparison",
                fill_summary_comparison,
                default="#009F81",
                options=list(
                    "black",
                    "#00C2F9",
                    "#008DF9",
                    "#009F81",
                    "#FF5AAF",
                    "#9F0162",
                    "#A40122",
                    "#00FCCF",
                    "#FF6E3A",
                    "#FFB2FD",
                    "#8400CD",
                    "#E20134",
                    "#FFC33B",
                    "white",
                    "NA",
                    "NA",
                    "gray0",
                    "gray5",
                    "gray10",
                    "gray15",
                    "gray20",
                    "gray25",
                    "gray30",
                    "gray35",
                    "gray40",
                    "gray45",
                    "gray50",
                    "gray55",
                    "gray60",
                    "gray65",
                    "gray70",
                    "gray75",
                    "gray80",
                    "gray85",
                    "gray90",
                    "gray95",
                    "gray100"))
            private$..fill_summary_difference <- jmvcore::OptionList$new(
                "fill_summary_difference",
                fill_summary_difference,
                default="black",
                options=list(
                    "black",
                    "#00C2F9",
                    "#008DF9",
                    "#009F81",
                    "#FF5AAF",
                    "#9F0162",
                    "#A40122",
                    "#00FCCF",
                    "#FF6E3A",
                    "#FFB2FD",
                    "#8400CD",
                    "#E20134",
                    "#FFC33B",
                    "white",
                    "NA",
                    "NA",
                    "gray0",
                    "gray5",
                    "gray10",
                    "gray15",
                    "gray20",
                    "gray25",
                    "gray30",
                    "gray35",
                    "gray40",
                    "gray45",
                    "gray50",
                    "gray55",
                    "gray60",
                    "gray65",
                    "gray70",
                    "gray75",
                    "gray80",
                    "gray85",
                    "gray90",
                    "gray95",
                    "gray100"))
            private$..size_summary_reference <- jmvcore::OptionList$new(
                "size_summary_reference",
                size_summary_reference,
                default="4",
                options=list(
                    "1",
                    "2",
                    "3",
                    "4",
                    "5",
                    "6"))
            private$..size_summary_comparison <- jmvcore::OptionList$new(
                "size_summary_comparison",
                size_summary_comparison,
                default="4",
                options=list(
                    "1",
                    "2",
                    "3",
                    "4",
                    "5",
                    "6"))
            private$..size_summary_difference <- jmvcore::OptionList$new(
                "size_summary_difference",
                size_summary_difference,
                default="4",
                options=list(
                    "1",
                    "2",
                    "3",
                    "4",
                    "5",
                    "6"))
            private$..alpha_summary_reference <- jmvcore::OptionList$new(
                "alpha_summary_reference",
                alpha_summary_reference,
                default="1",
                options=list(
                    "1",
                    ".75",
                    ".5",
                    ".25",
                    ".20",
                    ".15",
                    ".10",
                    ".05",
                    "0"))
            private$..alpha_summary_comparison <- jmvcore::OptionList$new(
                "alpha_summary_comparison",
                alpha_summary_comparison,
                default="1",
                options=list(
                    "1",
                    ".75",
                    ".5",
                    ".25",
                    ".20",
                    ".15",
                    ".10",
                    ".05",
                    "0"))
            private$..alpha_summary_difference <- jmvcore::OptionList$new(
                "alpha_summary_difference",
                alpha_summary_difference,
                default="1",
                options=list(
                    "1",
                    ".75",
                    ".5",
                    ".25",
                    ".20",
                    ".15",
                    ".10",
                    ".05",
                    "0"))
            private$..linetype_summary_reference <- jmvcore::OptionList$new(
                "linetype_summary_reference",
                linetype_summary_reference,
                default="solid",
                options=list(
                    "solid",
                    "dotted",
                    "dotdash",
                    "dashed",
                    "blank"))
            private$..linetype_summary_comparison <- jmvcore::OptionList$new(
                "linetype_summary_comparison",
                linetype_summary_comparison,
                default="solid",
                options=list(
                    "solid",
                    "dotted",
                    "dotdash",
                    "dashed",
                    "blank"))
            private$..linetype_summary_difference <- jmvcore::OptionList$new(
                "linetype_summary_difference",
                linetype_summary_difference,
                default="solid",
                options=list(
                    "solid",
                    "dotted",
                    "dotdash",
                    "dashed",
                    "blank"))

            self$.addOption(private$..switch)
            self$.addOption(private$..reference_measure)
            self$.addOption(private$..comparison_measure)
            self$.addOption(private$..cases_consistent)
            self$.addOption(private$..cases_inconsistent)
            self$.addOption(private$..not_cases_consistent)
            self$.addOption(private$..not_cases_inconsistent)
            self$.addOption(private$..case_label)
            self$.addOption(private$..not_case_label)
            self$.addOption(private$..comparison_measure_name)
            self$.addOption(private$..reference_measure_name)
            self$.addOption(private$..conf_level)
            self$.addOption(private$..show_details)
            self$.addOption(private$..evaluate_hypotheses)
            self$.addOption(private$..null_value)
            self$.addOption(private$..null_boundary)
            self$.addOption(private$..alpha)
            self$.addOption(private$..null_color)
            self$.addOption(private$..es_plot_width)
            self$.addOption(private$..es_plot_height)
            self$.addOption(private$..ymin)
            self$.addOption(private$..ymax)
            self$.addOption(private$..ybreaks)
            self$.addOption(private$..ylab)
            self$.addOption(private$..xlab)
            self$.addOption(private$..axis.text.y)
            self$.addOption(private$..axis.title.y)
            self$.addOption(private$..axis.text.x)
            self$.addOption(private$..axis.title.x)
            self$.addOption(private$..simple_contrast_labels)
            self$.addOption(private$..error_layout)
            self$.addOption(private$..difference_axis_breaks)
            self$.addOption(private$..shape_summary_reference)
            self$.addOption(private$..shape_summary_comparison)
            self$.addOption(private$..shape_summary_difference)
            self$.addOption(private$..color_summary_reference)
            self$.addOption(private$..color_summary_comparison)
            self$.addOption(private$..color_summary_difference)
            self$.addOption(private$..fill_summary_reference)
            self$.addOption(private$..fill_summary_comparison)
            self$.addOption(private$..fill_summary_difference)
            self$.addOption(private$..size_summary_reference)
            self$.addOption(private$..size_summary_comparison)
            self$.addOption(private$..size_summary_difference)
            self$.addOption(private$..alpha_summary_reference)
            self$.addOption(private$..alpha_summary_comparison)
            self$.addOption(private$..alpha_summary_difference)
            self$.addOption(private$..linetype_summary_reference)
            self$.addOption(private$..linetype_summary_comparison)
            self$.addOption(private$..linetype_summary_difference)
        }),
    active = list(
        switch = function() private$..switch$value,
        reference_measure = function() private$..reference_measure$value,
        comparison_measure = function() private$..comparison_measure$value,
        cases_consistent = function() private$..cases_consistent$value,
        cases_inconsistent = function() private$..cases_inconsistent$value,
        not_cases_consistent = function() private$..not_cases_consistent$value,
        not_cases_inconsistent = function() private$..not_cases_inconsistent$value,
        case_label = function() private$..case_label$value,
        not_case_label = function() private$..not_case_label$value,
        comparison_measure_name = function() private$..comparison_measure_name$value,
        reference_measure_name = function() private$..reference_measure_name$value,
        conf_level = function() private$..conf_level$value,
        show_details = function() private$..show_details$value,
        evaluate_hypotheses = function() private$..evaluate_hypotheses$value,
        null_value = function() private$..null_value$value,
        null_boundary = function() private$..null_boundary$value,
        alpha = function() private$..alpha$value,
        null_color = function() private$..null_color$value,
        es_plot_width = function() private$..es_plot_width$value,
        es_plot_height = function() private$..es_plot_height$value,
        ymin = function() private$..ymin$value,
        ymax = function() private$..ymax$value,
        ybreaks = function() private$..ybreaks$value,
        ylab = function() private$..ylab$value,
        xlab = function() private$..xlab$value,
        axis.text.y = function() private$..axis.text.y$value,
        axis.title.y = function() private$..axis.title.y$value,
        axis.text.x = function() private$..axis.text.x$value,
        axis.title.x = function() private$..axis.title.x$value,
        simple_contrast_labels = function() private$..simple_contrast_labels$value,
        error_layout = function() private$..error_layout$value,
        difference_axis_breaks = function() private$..difference_axis_breaks$value,
        shape_summary_reference = function() private$..shape_summary_reference$value,
        shape_summary_comparison = function() private$..shape_summary_comparison$value,
        shape_summary_difference = function() private$..shape_summary_difference$value,
        color_summary_reference = function() private$..color_summary_reference$value,
        color_summary_comparison = function() private$..color_summary_comparison$value,
        color_summary_difference = function() private$..color_summary_difference$value,
        fill_summary_reference = function() private$..fill_summary_reference$value,
        fill_summary_comparison = function() private$..fill_summary_comparison$value,
        fill_summary_difference = function() private$..fill_summary_difference$value,
        size_summary_reference = function() private$..size_summary_reference$value,
        size_summary_comparison = function() private$..size_summary_comparison$value,
        size_summary_difference = function() private$..size_summary_difference$value,
        alpha_summary_reference = function() private$..alpha_summary_reference$value,
        alpha_summary_comparison = function() private$..alpha_summary_comparison$value,
        alpha_summary_difference = function() private$..alpha_summary_difference$value,
        linetype_summary_reference = function() private$..linetype_summary_reference$value,
        linetype_summary_comparison = function() private$..linetype_summary_comparison$value,
        linetype_summary_difference = function() private$..linetype_summary_difference$value),
    private = list(
        ..switch = NA,
        ..reference_measure = NA,
        ..comparison_measure = NA,
        ..cases_consistent = NA,
        ..cases_inconsistent = NA,
        ..not_cases_consistent = NA,
        ..not_cases_inconsistent = NA,
        ..case_label = NA,
        ..not_case_label = NA,
        ..comparison_measure_name = NA,
        ..reference_measure_name = NA,
        ..conf_level = NA,
        ..show_details = NA,
        ..evaluate_hypotheses = NA,
        ..null_value = NA,
        ..null_boundary = NA,
        ..alpha = NA,
        ..null_color = NA,
        ..es_plot_width = NA,
        ..es_plot_height = NA,
        ..ymin = NA,
        ..ymax = NA,
        ..ybreaks = NA,
        ..ylab = NA,
        ..xlab = NA,
        ..axis.text.y = NA,
        ..axis.title.y = NA,
        ..axis.text.x = NA,
        ..axis.title.x = NA,
        ..simple_contrast_labels = NA,
        ..error_layout = NA,
        ..difference_axis_breaks = NA,
        ..shape_summary_reference = NA,
        ..shape_summary_comparison = NA,
        ..shape_summary_difference = NA,
        ..color_summary_reference = NA,
        ..color_summary_comparison = NA,
        ..color_summary_difference = NA,
        ..fill_summary_reference = NA,
        ..fill_summary_comparison = NA,
        ..fill_summary_difference = NA,
        ..size_summary_reference = NA,
        ..size_summary_comparison = NA,
        ..size_summary_difference = NA,
        ..alpha_summary_reference = NA,
        ..alpha_summary_comparison = NA,
        ..alpha_summary_difference = NA,
        ..linetype_summary_reference = NA,
        ..linetype_summary_comparison = NA,
        ..linetype_summary_difference = NA)
)

jamovipdiffpairedResults <- if (requireNamespace("jmvcore", quietly=TRUE)) R6::R6Class(
    "jamovipdiffpairedResults",
    inherit = jmvcore::Group,
    active = list(
        debug = function() private$.items[["debug"]],
        help = function() private$.items[["help"]],
        overview = function() private$.items[["overview"]],
        es_proportion_difference = function() private$.items[["es_proportion_difference"]],
        point_null = function() private$.items[["point_null"]],
        interval_null = function() private$.items[["interval_null"]],
        estimation_plot_warnings = function() private$.items[["estimation_plot_warnings"]],
        estimation_plots = function() private$.items[["estimation_plots"]]),
    private = list(),
    public=list(
        initialize=function(options) {
            super$initialize(
                options=options,
                name="",
                title="Proportions: Paired")
            self$add(jmvcore::Preformatted$new(
                options=options,
                name="debug",
                visible=TRUE))
            self$add(jmvcore::Html$new(
                options=options,
                name="help",
                visible=FALSE))
            self$add(jmvcore::Table$new(
                options=options,
                name="overview",
                title="Overview",
                rows=4,
                clearWith=list(
                    "reference_measure",
                    "comparison_measure",
                    "cases_consistent",
                    "cases_inconsistent",
                    "not_cases_consistent",
                    "not_cases_inconsistent",
                    "case_label",
                    "not_case_label",
                    "comparison_measure_name",
                    "reference_measure_name",
                    "conf_level",
                    "show_details"),
                columns=list(
                    list(
                        `name`="outcome_variable_name", 
                        `title`="Outcome variable name", 
                        `type`="text", 
                        `combineBelow`=TRUE),
                    list(
                        `name`="outcome_variable_level", 
                        `title`="Level", 
                        `type`="text", 
                        `combineBelow`=TRUE),
                    list(
                        `name`="cases", 
                        `title`="Cases", 
                        `type`="integer"),
                    list(
                        `name`="n", 
                        `title`="<i>N</i>", 
                        `type`="integer"),
                    list(
                        `name`="P", 
                        `title`="<i>P</i>", 
                        `type`="number"),
                    list(
                        `name`="P_LL", 
                        `title`="LL", 
                        `type`="number"),
                    list(
                        `name`="P_UL", 
                        `title`="UL", 
                        `type`="number"),
                    list(
                        `name`="P_SE", 
                        `type`="number", 
                        `title`="<i>SE</i><sub>Proportion</sub>", 
                        `visible`="(show_details)"),
                    list(
                        `name`="P_adjusted", 
                        `type`="number", 
                        `title`="<i>P</i><sub>adjusted</sub>", 
                        `visible`="(show_details)"))))
            self$add(jmvcore::Table$new(
                options=options,
                name="es_proportion_difference",
                title="Proportion Difference",
                rows=3,
                refs="prop_paired",
                clearWith=list(
                    "reference_measure",
                    "comparison_measure",
                    "cases_consistent",
                    "cases_inconsistent",
                    "not_cases_consistent",
                    "not_cases_inconsistent",
                    "case_label",
                    "not_case_label",
                    "comparison_measure_name",
                    "reference_measure_name",
                    "conf_level",
                    "show_details"),
                columns=list(
                    list(
                        `name`="effect_plus", 
                        `title`="Effect", 
                        `type`="text"),
                    list(
                        `name`="effect_size", 
                        `type`="number", 
                        `title`="<i>P</i>"),
                    list(
                        `name`="LL", 
                        `title`="LL", 
                        `type`="number"),
                    list(
                        `name`="UL", 
                        `title`="UL", 
                        `type`="number"),
                    list(
                        `name`="SE", 
                        `title`="<i>SE</i><sub>Proportion</sub>", 
                        `type`="number", 
                        `visible`="(show_details)"),
                    list(
                        `name`="effect_size_adjusted", 
                        `title`="<i>P</i><sub>adjusted</sub>", 
                        `type`="number", 
                        `visible`="(show_details)"))))
            self$add(jmvcore::Table$new(
                options=options,
                name="point_null",
                title="Hypothesis Evaluation",
                rows=1,
                visible="(evaluate_hypotheses & null_boundary == 0)",
                clearWith=list(
                    "reference_measure",
                    "comparison_measure",
                    "cases_consistent",
                    "cases_inconsistent",
                    "not_cases_consistent",
                    "not_cases_inconsistent",
                    "case_label",
                    "not_case_label",
                    "comparison_measure_name",
                    "reference_measure_name",
                    "conf_level",
                    "show_details",
                    "null_value",
                    "null_boundary"),
                columns=list(
                    list(
                        `name`="effect_plus", 
                        `title`="Effect", 
                        `type`="text", 
                        `combineBelow`=FALSE),
                    list(
                        `name`="null_words", 
                        `title`="<i>H</i><sub>0</sub>", 
                        `type`="text"),
                    list(
                        `name`="CI", 
                        `title`="CI", 
                        `type`="text"),
                    list(
                        `name`="CI_compare", 
                        `title`="Compare CI with <i>H</i><sub>0</sub>", 
                        `type`="text"),
                    list(
                        `name`="t", 
                        `title`="<i>z</i>", 
                        `type`="number"),
                    list(
                        `name`="p", 
                        `title`="<i>p</i>, two-tailed", 
                        `type`="number", 
                        `format`="zto,pvalue"),
                    list(
                        `name`="null_decision", 
                        `title`="<i>H</i><sub>0</sub> decision"),
                    list(
                        `name`="conclusion", 
                        `title`="Conclusion", 
                        `type`="text"))))
            self$add(jmvcore::Table$new(
                options=options,
                name="interval_null",
                title="Hypothesis Evaluation",
                rows=1,
                visible="(evaluate_hypotheses & null_boundary != 0)",
                clearWith=list(
                    "reference_measure",
                    "comparison_measure",
                    "cases_consistent",
                    "cases_inconsistent",
                    "not_cases_consistent",
                    "not_cases_inconsistent",
                    "case_label",
                    "not_case_label",
                    "comparison_measure_name",
                    "reference_measure_name",
                    "conf_level",
                    "show_details",
                    "null_value",
                    "null_boundary"),
                columns=list(
                    list(
                        `name`="effect_plus", 
                        `title`="Effect", 
                        `type`="text", 
                        `combineBelow`=FALSE),
                    list(
                        `name`="rope", 
                        `title`="<i>H</i><sub>0</sub>", 
                        `type`="text"),
                    list(
                        `name`="CI", 
                        `title`="CI", 
                        `type`="text"),
                    list(
                        `name`="rope_compare", 
                        `title`="Compare CI with <i>H</i><sub>0</sub>", 
                        `type`="text"),
                    list(
                        `name`="p_result", 
                        `title`="<i>p</i>, two tailed", 
                        `type`="text"),
                    list(
                        `name`="conclusion", 
                        `title`="Conclusion", 
                        `type`="text"))))
            self$add(jmvcore::Html$new(
                options=options,
                name="estimation_plot_warnings",
                title="Estimation Figure Warnings",
                visible=TRUE))
            self$add(jmvcore::Image$new(
                options=options,
                name="estimation_plots",
                title="Estimation Figure",
                width=300,
                height=450,
                requiresData=TRUE,
                refs="ggdist",
                renderFun=".estimation_plots"))}))

jamovipdiffpairedBase <- if (requireNamespace("jmvcore", quietly=TRUE)) R6::R6Class(
    "jamovipdiffpairedBase",
    inherit = jmvcore::Analysis,
    public = list(
        initialize = function(options, data=NULL, datasetId="", analysisId="", revision=0) {
            super$initialize(
                package = "esci",
                name = "jamovipdiffpaired",
                version = c(1,0,0),
                options = options,
                results = jamovipdiffpairedResults$new(options=options),
                data = data,
                datasetId = datasetId,
                analysisId = analysisId,
                revision = revision,
                pause = NULL,
                completeWhenFilled = FALSE,
                requiresMissings = FALSE,
                weightsSupport = 'auto')
        }))

#' Proportions: Paired
#'
#' 
#' @param switch .
#' @param data .
#' @param reference_measure .
#' @param comparison_measure .
#' @param cases_consistent .
#' @param cases_inconsistent .
#' @param not_cases_consistent .
#' @param not_cases_inconsistent .
#' @param case_label .
#' @param not_case_label .
#' @param comparison_measure_name .
#' @param reference_measure_name .
#' @param conf_level .
#' @param show_details .
#' @param evaluate_hypotheses .
#' @param null_value .
#' @param null_boundary .
#' @param alpha .
#' @param null_color .
#' @param es_plot_width .
#' @param es_plot_height .
#' @param ymin .
#' @param ymax .
#' @param ybreaks .
#' @param ylab .
#' @param xlab .
#' @param axis.text.y .
#' @param axis.title.y .
#' @param axis.text.x .
#' @param axis.title.x .
#' @param simple_contrast_labels .
#' @param error_layout .
#' @param difference_axis_breaks .
#' @param shape_summary_reference .
#' @param shape_summary_comparison .
#' @param shape_summary_difference .
#' @param color_summary_reference .
#' @param color_summary_comparison .
#' @param color_summary_difference .
#' @param fill_summary_reference .
#' @param fill_summary_comparison .
#' @param fill_summary_difference .
#' @param size_summary_reference .
#' @param size_summary_comparison .
#' @param size_summary_difference .
#' @param alpha_summary_reference .
#' @param alpha_summary_comparison .
#' @param alpha_summary_difference .
#' @param linetype_summary_reference .
#' @param linetype_summary_comparison .
#' @param linetype_summary_difference .
#' @return A results object containing:
#' \tabular{llllll}{
#'   \code{results$debug} \tab \tab \tab \tab \tab a preformatted \cr
#'   \code{results$help} \tab \tab \tab \tab \tab a html \cr
#'   \code{results$overview} \tab \tab \tab \tab \tab a table \cr
#'   \code{results$es_proportion_difference} \tab \tab \tab \tab \tab a table \cr
#'   \code{results$point_null} \tab \tab \tab \tab \tab a table \cr
#'   \code{results$interval_null} \tab \tab \tab \tab \tab a table \cr
#'   \code{results$estimation_plot_warnings} \tab \tab \tab \tab \tab a html \cr
#'   \code{results$estimation_plots} \tab \tab \tab \tab \tab an image \cr
#' }
#'
#' Tables can be converted to data frames with \code{asDF} or \code{\link{as.data.frame}}. For example:
#'
#' \code{results$overview$asDF}
#'
#' \code{as.data.frame(results$overview)}
#'
#' @export
jamovipdiffpaired <- function(
    switch = "from_raw",
    data,
    reference_measure,
    comparison_measure,
    cases_consistent = " ",
    cases_inconsistent = " ",
    not_cases_consistent = " ",
    not_cases_inconsistent = " ",
    case_label = "Sick",
    not_case_label = "Well",
    comparison_measure_name = "Post-test",
    reference_measure_name = "Pre-test",
    conf_level = 95,
    show_details = FALSE,
    evaluate_hypotheses = FALSE,
    null_value = "0",
    null_boundary = "0",
    alpha = 0.05,
    null_color = "#A40122",
    es_plot_width = "400",
    es_plot_height = "450",
    ymin = "auto",
    ymax = "auto",
    ybreaks = "auto",
    ylab = "auto",
    xlab = "auto",
    axis.text.y = "14",
    axis.title.y = "15",
    axis.text.x = "14",
    axis.title.x = "15",
    simple_contrast_labels = TRUE,
    error_layout = "none",
    difference_axis_breaks = "auto",
    shape_summary_reference = "circle filled",
    shape_summary_comparison = "circle filled",
    shape_summary_difference = "triangle filled",
    color_summary_reference = "#008DF9",
    color_summary_comparison = "#009F81",
    color_summary_difference = "black",
    fill_summary_reference = "#008DF9",
    fill_summary_comparison = "#009F81",
    fill_summary_difference = "black",
    size_summary_reference = "4",
    size_summary_comparison = "4",
    size_summary_difference = "4",
    alpha_summary_reference = "1",
    alpha_summary_comparison = "1",
    alpha_summary_difference = "1",
    linetype_summary_reference = "solid",
    linetype_summary_comparison = "solid",
    linetype_summary_difference = "solid") {

    if ( ! requireNamespace("jmvcore", quietly=TRUE))
        stop("jamovipdiffpaired requires jmvcore to be installed (restart may be required)")

    if ( ! missing(reference_measure)) reference_measure <- jmvcore::resolveQuo(jmvcore::enquo(reference_measure))
    if ( ! missing(comparison_measure)) comparison_measure <- jmvcore::resolveQuo(jmvcore::enquo(comparison_measure))
    if (missing(data))
        data <- jmvcore::marshalData(
            parent.frame(),
            `if`( ! missing(reference_measure), reference_measure, NULL),
            `if`( ! missing(comparison_measure), comparison_measure, NULL))

    for (v in reference_measure) if (v %in% names(data)) data[[v]] <- as.factor(data[[v]])
    for (v in comparison_measure) if (v %in% names(data)) data[[v]] <- as.factor(data[[v]])

    options <- jamovipdiffpairedOptions$new(
        switch = switch,
        reference_measure = reference_measure,
        comparison_measure = comparison_measure,
        cases_consistent = cases_consistent,
        cases_inconsistent = cases_inconsistent,
        not_cases_consistent = not_cases_consistent,
        not_cases_inconsistent = not_cases_inconsistent,
        case_label = case_label,
        not_case_label = not_case_label,
        comparison_measure_name = comparison_measure_name,
        reference_measure_name = reference_measure_name,
        conf_level = conf_level,
        show_details = show_details,
        evaluate_hypotheses = evaluate_hypotheses,
        null_value = null_value,
        null_boundary = null_boundary,
        alpha = alpha,
        null_color = null_color,
        es_plot_width = es_plot_width,
        es_plot_height = es_plot_height,
        ymin = ymin,
        ymax = ymax,
        ybreaks = ybreaks,
        ylab = ylab,
        xlab = xlab,
        axis.text.y = axis.text.y,
        axis.title.y = axis.title.y,
        axis.text.x = axis.text.x,
        axis.title.x = axis.title.x,
        simple_contrast_labels = simple_contrast_labels,
        error_layout = error_layout,
        difference_axis_breaks = difference_axis_breaks,
        shape_summary_reference = shape_summary_reference,
        shape_summary_comparison = shape_summary_comparison,
        shape_summary_difference = shape_summary_difference,
        color_summary_reference = color_summary_reference,
        color_summary_comparison = color_summary_comparison,
        color_summary_difference = color_summary_difference,
        fill_summary_reference = fill_summary_reference,
        fill_summary_comparison = fill_summary_comparison,
        fill_summary_difference = fill_summary_difference,
        size_summary_reference = size_summary_reference,
        size_summary_comparison = size_summary_comparison,
        size_summary_difference = size_summary_difference,
        alpha_summary_reference = alpha_summary_reference,
        alpha_summary_comparison = alpha_summary_comparison,
        alpha_summary_difference = alpha_summary_difference,
        linetype_summary_reference = linetype_summary_reference,
        linetype_summary_comparison = linetype_summary_comparison,
        linetype_summary_difference = linetype_summary_difference)

    analysis <- jamovipdiffpairedClass$new(
        options = options,
        data = data)

    analysis$run()

    analysis$results
}

