
# This file is automatically generated, you probably don't want to edit this

jmvEstimateProportionDifferenceOptions <- if (requireNamespace('jmvcore')) R6::R6Class(
    "jmvEstimateProportionDifferenceOptions",
    inherit = jmvcore::Options,
    public = list(
        initialize = function(
            switch = "fromraw",
            measure1 = NULL,
            measure2 = NULL,
            case.level = NULL,
            category.level = NULL,
            cases1 = NULL,
            n1 = NULL,
            cases2 = NULL,
            n2 = NULL,
            caselabel1 = "Affected",
            caselabel2 = "Not affected",
            grouplabel1 = "Group 1",
            grouplabel2 = "Group 2",
            conf.level = 95,
            ylab = "auto",
            xlab = "auto",
            ropeBottom = "none",
            ropeTop = "none", ...) {

            super$initialize(
                package='esci',
                name='jmvEstimateProportionDifference',
                requiresData=TRUE,
                ...)

            private$..switch <- jmvcore::OptionList$new(
                "switch",
                switch,
                default="fromraw",
                options=list(
                    "fromraw",
                    "fromsummary"))
            private$..measure1 <- jmvcore::OptionVariable$new(
                "measure1",
                measure1)
            private$..measure2 <- jmvcore::OptionVariable$new(
                "measure2",
                measure2)
            private$..case.level <- jmvcore::OptionString$new(
                "case.level",
                case.level)
            private$..category.level <- jmvcore::OptionString$new(
                "category.level",
                category.level)
            private$..cases1 <- jmvcore::OptionInteger$new(
                "cases1",
                cases1)
            private$..n1 <- jmvcore::OptionInteger$new(
                "n1",
                n1)
            private$..cases2 <- jmvcore::OptionInteger$new(
                "cases2",
                cases2)
            private$..n2 <- jmvcore::OptionInteger$new(
                "n2",
                n2)
            private$..caselabel1 <- jmvcore::OptionString$new(
                "caselabel1",
                caselabel1,
                default="Affected")
            private$..caselabel2 <- jmvcore::OptionString$new(
                "caselabel2",
                caselabel2,
                default="Not affected")
            private$..grouplabel1 <- jmvcore::OptionString$new(
                "grouplabel1",
                grouplabel1,
                default="Group 1")
            private$..grouplabel2 <- jmvcore::OptionString$new(
                "grouplabel2",
                grouplabel2,
                default="Group 2")
            private$..conf.level <- jmvcore::OptionNumber$new(
                "conf.level",
                conf.level,
                min=50,
                max=99.9999,
                default=95)
            private$..ylab <- jmvcore::OptionString$new(
                "ylab",
                ylab,
                default="auto")
            private$..xlab <- jmvcore::OptionString$new(
                "xlab",
                xlab,
                default="auto")
            private$..ropeBottom <- jmvcore::OptionString$new(
                "ropeBottom",
                ropeBottom,
                default="none")
            private$..ropeTop <- jmvcore::OptionString$new(
                "ropeTop",
                ropeTop,
                default="none")

            self$.addOption(private$..switch)
            self$.addOption(private$..measure1)
            self$.addOption(private$..measure2)
            self$.addOption(private$..case.level)
            self$.addOption(private$..category.level)
            self$.addOption(private$..cases1)
            self$.addOption(private$..n1)
            self$.addOption(private$..cases2)
            self$.addOption(private$..n2)
            self$.addOption(private$..caselabel1)
            self$.addOption(private$..caselabel2)
            self$.addOption(private$..grouplabel1)
            self$.addOption(private$..grouplabel2)
            self$.addOption(private$..conf.level)
            self$.addOption(private$..ylab)
            self$.addOption(private$..xlab)
            self$.addOption(private$..ropeBottom)
            self$.addOption(private$..ropeTop)
        }),
    active = list(
        switch = function() private$..switch$value,
        measure1 = function() private$..measure1$value,
        measure2 = function() private$..measure2$value,
        case.level = function() private$..case.level$value,
        category.level = function() private$..category.level$value,
        cases1 = function() private$..cases1$value,
        n1 = function() private$..n1$value,
        cases2 = function() private$..cases2$value,
        n2 = function() private$..n2$value,
        caselabel1 = function() private$..caselabel1$value,
        caselabel2 = function() private$..caselabel2$value,
        grouplabel1 = function() private$..grouplabel1$value,
        grouplabel2 = function() private$..grouplabel2$value,
        conf.level = function() private$..conf.level$value,
        ylab = function() private$..ylab$value,
        xlab = function() private$..xlab$value,
        ropeBottom = function() private$..ropeBottom$value,
        ropeTop = function() private$..ropeTop$value),
    private = list(
        ..switch = NA,
        ..measure1 = NA,
        ..measure2 = NA,
        ..case.level = NA,
        ..category.level = NA,
        ..cases1 = NA,
        ..n1 = NA,
        ..cases2 = NA,
        ..n2 = NA,
        ..caselabel1 = NA,
        ..caselabel2 = NA,
        ..grouplabel1 = NA,
        ..grouplabel2 = NA,
        ..conf.level = NA,
        ..ylab = NA,
        ..xlab = NA,
        ..ropeBottom = NA,
        ..ropeTop = NA)
)

jmvEstimateProportionDifferenceResults <- if (requireNamespace('jmvcore')) R6::R6Class(
    inherit = jmvcore::Group,
    active = list(
        text = function() private$.items[["text"]],
        summary_table = function() private$.items[["summary_table"]],
        proportion_plot = function() private$.items[["proportion_plot"]]),
    private = list(),
    public=list(
        initialize=function(options) {
            super$initialize(
                options=options,
                name="",
                title="Estimate Proportion Difference")
            self$add(jmvcore::Html$new(
                options=options,
                name="text",
                title="Instructions/Errors",
                visible=FALSE))
            self$add(jmvcore::Table$new(
                options=options,
                name="summary_table",
                title="Estimated Difference in Proportion",
                rows=3,
                visible=TRUE,
                columns=list(
                    list(
                        `name`="var", 
                        `title`="", 
                        `type`="text"),
                    list(
                        `name`="cases", 
                        `title`="Cases", 
                        `type`="integer"),
                    list(
                        `name`="ncases", 
                        `title`="NotCases", 
                        `type`="integer"),
                    list(
                        `name`="n", 
                        `title`="Total N", 
                        `type`="integer"),
                    list(
                        `name`="P", 
                        `title`="P", 
                        `type`="number"),
                    list(
                        `name`="ci.low", 
                        `title`="Lower", 
                        `type`="number"),
                    list(
                        `name`="ci.high", 
                        `title`="Upper", 
                        `type`="number"))))
            self$add(jmvcore::Image$new(
                options=options,
                name="proportion_plot",
                title="Proportion Plot",
                visible=TRUE,
                width=300,
                height=530,
                renderFun=".plot"))}))

jmvEstimateProportionDifferenceBase <- if (requireNamespace('jmvcore')) R6::R6Class(
    "jmvEstimateProportionDifferenceBase",
    inherit = jmvcore::Analysis,
    public = list(
        initialize = function(options, data=NULL, datasetId="", analysisId="", revision=0) {
            super$initialize(
                package = 'esci',
                name = 'jmvEstimateProportionDifference',
                version = c(1,0,0),
                options = options,
                results = jmvEstimateProportionDifferenceResults$new(options=options),
                data = data,
                datasetId = datasetId,
                analysisId = analysisId,
                revision = revision,
                pause = NULL,
                completeWhenFilled = FALSE,
                requiresMissings = FALSE)
        }))

#' Estimate Proportion Difference
#'
#' 
#' @param switch .
#' @param data .
#' @param measure1 .
#' @param measure2 .
#' @param case.level .
#' @param category.level .
#' @param cases1 .
#' @param n1 .
#' @param cases2 .
#' @param n2 .
#' @param caselabel1 .
#' @param caselabel2 .
#' @param grouplabel1 .
#' @param grouplabel2 .
#' @param conf.level .
#' @param ylab .
#' @param xlab .
#' @param ropeBottom .
#' @param ropeTop .
#' @return A results object containing:
#' \tabular{llllll}{
#'   \code{results$text} \tab \tab \tab \tab \tab a html \cr
#'   \code{results$summary_table} \tab \tab \tab \tab \tab a table \cr
#'   \code{results$proportion_plot} \tab \tab \tab \tab \tab an image \cr
#' }
#'
#' Tables can be converted to data frames with \code{asDF} or \code{\link{as.data.frame}}. For example:
#'
#' \code{results$summary_table$asDF}
#'
#' \code{as.data.frame(results$summary_table)}
#'
#' @export
jmvEstimateProportionDifference <- function(
    switch = "fromraw",
    data,
    measure1,
    measure2,
    case.level,
    category.level,
    cases1,
    n1,
    cases2,
    n2,
    caselabel1 = "Affected",
    caselabel2 = "Not affected",
    grouplabel1 = "Group 1",
    grouplabel2 = "Group 2",
    conf.level = 95,
    ylab = "auto",
    xlab = "auto",
    ropeBottom = "none",
    ropeTop = "none") {

    if ( ! requireNamespace('jmvcore'))
        stop('jmvEstimateProportionDifference requires jmvcore to be installed (restart may be required)')

    if ( ! missing(measure1)) measure1 <- jmvcore::resolveQuo(jmvcore::enquo(measure1))
    if ( ! missing(measure2)) measure2 <- jmvcore::resolveQuo(jmvcore::enquo(measure2))
    if (missing(data))
        data <- jmvcore::marshalData(
            parent.frame(),
            `if`( ! missing(measure1), measure1, NULL),
            `if`( ! missing(measure2), measure2, NULL))


    options <- jmvEstimateProportionDifferenceOptions$new(
        switch = switch,
        measure1 = measure1,
        measure2 = measure2,
        case.level = case.level,
        category.level = category.level,
        cases1 = cases1,
        n1 = n1,
        cases2 = cases2,
        n2 = n2,
        caselabel1 = caselabel1,
        caselabel2 = caselabel2,
        grouplabel1 = grouplabel1,
        grouplabel2 = grouplabel2,
        conf.level = conf.level,
        ylab = ylab,
        xlab = xlab,
        ropeBottom = ropeBottom,
        ropeTop = ropeTop)

    analysis <- jmvEstimateProportionDifferenceClass$new(
        options = options,
        data = data)

    analysis$run()

    analysis$results
}
