
# This file is automatically generated, you probably don't want to edit this

jmvEstimateProportionOptions <- if (requireNamespace('jmvcore')) R6::R6Class(
    "jmvEstimateProportionOptions",
    inherit = jmvcore::Options,
    public = list(
        initialize = function(
            switch = "fromraw",
            measure1 = NULL,
            case.level = NULL,
            na.rm = "remove",
            cases = NULL,
            n = NULL,
            caselabel1 = "Affected",
            caselabel2 = "Not affected",
            conf.level = 95,
            ylab = "auto",
            xlab = "auto",
            ropeBottom = "none",
            ropeTop = "none", ...) {

            super$initialize(
                package='esci',
                name='jmvEstimateProportion',
                requiresData=TRUE,
                ...)

            private$..switch <- jmvcore::OptionList$new(
                "switch",
                switch,
                default="fromraw",
                options=list(
                    "fromraw",
                    "fromsummary"))
            private$..measure1 <- jmvcore::OptionVariable$new(
                "measure1",
                measure1)
            private$..case.level <- jmvcore::OptionString$new(
                "case.level",
                case.level)
            private$..na.rm <- jmvcore::OptionList$new(
                "na.rm",
                na.rm,
                default="remove",
                options=list(
                    "remove",
                    "dontremove"))
            private$..cases <- jmvcore::OptionInteger$new(
                "cases",
                cases)
            private$..n <- jmvcore::OptionInteger$new(
                "n",
                n)
            private$..caselabel1 <- jmvcore::OptionString$new(
                "caselabel1",
                caselabel1,
                default="Affected")
            private$..caselabel2 <- jmvcore::OptionString$new(
                "caselabel2",
                caselabel2,
                default="Not affected")
            private$..conf.level <- jmvcore::OptionNumber$new(
                "conf.level",
                conf.level,
                min=50,
                max=99.9999,
                default=95)
            private$..ylab <- jmvcore::OptionString$new(
                "ylab",
                ylab,
                default="auto")
            private$..xlab <- jmvcore::OptionString$new(
                "xlab",
                xlab,
                default="auto")
            private$..ropeBottom <- jmvcore::OptionString$new(
                "ropeBottom",
                ropeBottom,
                default="none")
            private$..ropeTop <- jmvcore::OptionString$new(
                "ropeTop",
                ropeTop,
                default="none")

            self$.addOption(private$..switch)
            self$.addOption(private$..measure1)
            self$.addOption(private$..case.level)
            self$.addOption(private$..na.rm)
            self$.addOption(private$..cases)
            self$.addOption(private$..n)
            self$.addOption(private$..caselabel1)
            self$.addOption(private$..caselabel2)
            self$.addOption(private$..conf.level)
            self$.addOption(private$..ylab)
            self$.addOption(private$..xlab)
            self$.addOption(private$..ropeBottom)
            self$.addOption(private$..ropeTop)
        }),
    active = list(
        switch = function() private$..switch$value,
        measure1 = function() private$..measure1$value,
        case.level = function() private$..case.level$value,
        na.rm = function() private$..na.rm$value,
        cases = function() private$..cases$value,
        n = function() private$..n$value,
        caselabel1 = function() private$..caselabel1$value,
        caselabel2 = function() private$..caselabel2$value,
        conf.level = function() private$..conf.level$value,
        ylab = function() private$..ylab$value,
        xlab = function() private$..xlab$value,
        ropeBottom = function() private$..ropeBottom$value,
        ropeTop = function() private$..ropeTop$value),
    private = list(
        ..switch = NA,
        ..measure1 = NA,
        ..case.level = NA,
        ..na.rm = NA,
        ..cases = NA,
        ..n = NA,
        ..caselabel1 = NA,
        ..caselabel2 = NA,
        ..conf.level = NA,
        ..ylab = NA,
        ..xlab = NA,
        ..ropeBottom = NA,
        ..ropeTop = NA)
)

jmvEstimateProportionResults <- if (requireNamespace('jmvcore')) R6::R6Class(
    inherit = jmvcore::Group,
    active = list(
        text = function() private$.items[["text"]],
        summary_table = function() private$.items[["summary_table"]],
        bar_plot = function() private$.items[["bar_plot"]],
        proportion_plot = function() private$.items[["proportion_plot"]]),
    private = list(),
    public=list(
        initialize=function(options) {
            super$initialize(
                options=options,
                name="",
                title="Estimate Proportion")
            self$add(jmvcore::Html$new(
                options=options,
                name="text",
                title="Instructions/Errors",
                visible=FALSE))
            self$add(jmvcore::Table$new(
                options=options,
                name="summary_table",
                title="Estimated Proportion",
                rows=0,
                columns=list(
                    list(
                        `name`="var", 
                        `title`="Group", 
                        `type`="text"))))
            self$add(jmvcore::Image$new(
                options=options,
                name="bar_plot",
                title="Frequency Plot",
                width=530,
                height=300,
                renderFun=".bplot"))
            self$add(jmvcore::Image$new(
                options=options,
                name="proportion_plot",
                title="Proportion Plot",
                width=300,
                height=530,
                renderFun=".plot"))}))

jmvEstimateProportionBase <- if (requireNamespace('jmvcore')) R6::R6Class(
    "jmvEstimateProportionBase",
    inherit = jmvcore::Analysis,
    public = list(
        initialize = function(options, data=NULL, datasetId="", analysisId="", revision=0) {
            super$initialize(
                package = 'esci',
                name = 'jmvEstimateProportion',
                version = c(1,0,0),
                options = options,
                results = jmvEstimateProportionResults$new(options=options),
                data = data,
                datasetId = datasetId,
                analysisId = analysisId,
                revision = revision,
                pause = NULL,
                completeWhenFilled = FALSE,
                requiresMissings = FALSE)
        }))

#' Estimate Proportion
#'
#' 
#' @param switch .
#' @param data .
#' @param measure1 .
#' @param case.level .
#' @param na.rm .
#' @param cases .
#' @param n .
#' @param caselabel1 .
#' @param caselabel2 .
#' @param conf.level .
#' @param ylab .
#' @param xlab .
#' @param ropeBottom .
#' @param ropeTop .
#' @return A results object containing:
#' \tabular{llllll}{
#'   \code{results$text} \tab \tab \tab \tab \tab a html \cr
#'   \code{results$summary_table} \tab \tab \tab \tab \tab a table \cr
#'   \code{results$bar_plot} \tab \tab \tab \tab \tab an image \cr
#'   \code{results$proportion_plot} \tab \tab \tab \tab \tab an image \cr
#' }
#'
#' Tables can be converted to data frames with \code{asDF} or \code{\link{as.data.frame}}. For example:
#'
#' \code{results$summary_table$asDF}
#'
#' \code{as.data.frame(results$summary_table)}
#'
#' @export
jmvEstimateProportion <- function(
    switch = "fromraw",
    data,
    measure1,
    case.level,
    na.rm = "remove",
    cases,
    n,
    caselabel1 = "Affected",
    caselabel2 = "Not affected",
    conf.level = 95,
    ylab = "auto",
    xlab = "auto",
    ropeBottom = "none",
    ropeTop = "none") {

    if ( ! requireNamespace('jmvcore'))
        stop('jmvEstimateProportion requires jmvcore to be installed (restart may be required)')

    if ( ! missing(measure1)) measure1 <- jmvcore::resolveQuo(jmvcore::enquo(measure1))
    if (missing(data))
        data <- jmvcore::marshalData(
            parent.frame(),
            `if`( ! missing(measure1), measure1, NULL))


    options <- jmvEstimateProportionOptions$new(
        switch = switch,
        measure1 = measure1,
        case.level = case.level,
        na.rm = na.rm,
        cases = cases,
        n = n,
        caselabel1 = caselabel1,
        caselabel2 = caselabel2,
        conf.level = conf.level,
        ylab = ylab,
        xlab = xlab,
        ropeBottom = ropeBottom,
        ropeTop = ropeTop)

    analysis <- jmvEstimateProportionClass$new(
        options = options,
        data = data)

    analysis$run()

    analysis$results
}
