
# This file is automatically generated, you probably don't want to edit this

jmvMetaAnalysisROptions <- if (requireNamespace('jmvcore')) R6::R6Class(
    "jmvMetaAnalysisROptions",
    inherit = jmvcore::Options,
    public = list(
        initialize = function(
            labels = NULL,
            r = NULL,
            n = NULL,
            moderator = NULL,
            REorFE = "RE",
            conf.level = 0.95,
            show.study.table = FALSE, ...) {

            super$initialize(
                package='esci',
                name='jmvMetaAnalysisR',
                requiresData=TRUE,
                ...)

            private$..labels <- jmvcore::OptionVariable$new(
                "labels",
                labels)
            private$..r <- jmvcore::OptionVariable$new(
                "r",
                r)
            private$..n <- jmvcore::OptionVariable$new(
                "n",
                n)
            private$..moderator <- jmvcore::OptionVariable$new(
                "moderator",
                moderator)
            private$..REorFE <- jmvcore::OptionList$new(
                "REorFE",
                REorFE,
                options=list(
                    "RE",
                    "FE"),
                default="RE")
            private$..conf.level <- jmvcore::OptionNumber$new(
                "conf.level",
                conf.level,
                min=0.5,
                max=0.999999,
                default=0.95)
            private$..show.study.table <- jmvcore::OptionBool$new(
                "show.study.table",
                show.study.table,
                default=FALSE)

            self$.addOption(private$..labels)
            self$.addOption(private$..r)
            self$.addOption(private$..n)
            self$.addOption(private$..moderator)
            self$.addOption(private$..REorFE)
            self$.addOption(private$..conf.level)
            self$.addOption(private$..show.study.table)
        }),
    active = list(
        labels = function() private$..labels$value,
        r = function() private$..r$value,
        n = function() private$..n$value,
        moderator = function() private$..moderator$value,
        REorFE = function() private$..REorFE$value,
        conf.level = function() private$..conf.level$value,
        show.study.table = function() private$..show.study.table$value),
    private = list(
        ..labels = NA,
        ..r = NA,
        ..n = NA,
        ..moderator = NA,
        ..REorFE = NA,
        ..conf.level = NA,
        ..show.study.table = NA)
)

jmvMetaAnalysisRResults <- if (requireNamespace('jmvcore')) R6::R6Class(
    inherit = jmvcore::Group,
    active = list(
        text = function() private$.items[["text"]],
        result_table = function() private$.items[["result_table"]],
        study_table = function() private$.items[["study_table"]],
        forest_plot = function() private$.items[["forest_plot"]]),
    private = list(),
    public=list(
        initialize=function(options) {
            super$initialize(
                options=options,
                name="",
                title="Meta-Analysis - r")
            self$add(jmvcore::Preformatted$new(
                options=options,
                name="text",
                title="Instructions/Errros",
                visible=TRUE))
            self$add(jmvcore::Table$new(
                options=options,
                name="result_table",
                title="Meta-Analysis Results",
                visible=TRUE,
                rows=0,
                columns=list(
                    list(
                        `name`="label", 
                        `title`="Label", 
                        `type`="text"))))
            self$add(jmvcore::Table$new(
                options=options,
                name="study_table",
                title="Table of Studies",
                visible=TRUE,
                rows=0,
                columns=list(
                    list(
                        `name`="label", 
                        `title`="Label", 
                        `type`="text"))))
            self$add(jmvcore::Image$new(
                options=options,
                name="forest_plot",
                title="Forest Plot",
                visible=TRUE,
                width=500,
                height=800,
                renderFun=".plot"))}))

jmvMetaAnalysisRBase <- if (requireNamespace('jmvcore')) R6::R6Class(
    "jmvMetaAnalysisRBase",
    inherit = jmvcore::Analysis,
    public = list(
        initialize = function(options, data=NULL, datasetId="", analysisId="", revision=0) {
            super$initialize(
                package = 'esci',
                name = 'jmvMetaAnalysisR',
                version = c(1,0,0),
                options = options,
                results = jmvMetaAnalysisRResults$new(options=options),
                data = data,
                datasetId = datasetId,
                analysisId = analysisId,
                revision = revision,
                pause = NULL,
                completeWhenFilled = FALSE,
                requiresMissings = FALSE)
        }))

#' Meta-Analysis - r
#'
#' 
#' @param data .
#' @param labels .
#' @param r .
#' @param n .
#' @param moderator .
#' @param REorFE .
#' @param conf.level .
#' @param show.study.table .
#' @return A results object containing:
#' \tabular{llllll}{
#'   \code{results$text} \tab \tab \tab \tab \tab a preformatted \cr
#'   \code{results$result_table} \tab \tab \tab \tab \tab a table \cr
#'   \code{results$study_table} \tab \tab \tab \tab \tab a table \cr
#'   \code{results$forest_plot} \tab \tab \tab \tab \tab an image \cr
#' }
#'
#' Tables can be converted to data frames with \code{asDF} or \code{\link{as.data.frame}}. For example:
#'
#' \code{results$result_table$asDF}
#'
#' \code{as.data.frame(results$result_table)}
#'
#' @export
jmvMetaAnalysisR <- function(
    data,
    labels,
    r,
    n,
    moderator,
    REorFE = "RE",
    conf.level = 0.95,
    show.study.table = FALSE) {

    if ( ! requireNamespace('jmvcore'))
        stop('jmvMetaAnalysisR requires jmvcore to be installed (restart may be required)')

    if ( ! missing(labels)) labels <- jmvcore::resolveQuo(jmvcore::enquo(labels))
    if ( ! missing(r)) r <- jmvcore::resolveQuo(jmvcore::enquo(r))
    if ( ! missing(n)) n <- jmvcore::resolveQuo(jmvcore::enquo(n))
    if ( ! missing(moderator)) moderator <- jmvcore::resolveQuo(jmvcore::enquo(moderator))
    if (missing(data))
        data <- jmvcore::marshalData(
            parent.frame(),
            `if`( ! missing(labels), labels, NULL),
            `if`( ! missing(r), r, NULL),
            `if`( ! missing(n), n, NULL),
            `if`( ! missing(moderator), moderator, NULL))


    options <- jmvMetaAnalysisROptions$new(
        labels = labels,
        r = r,
        n = n,
        moderator = moderator,
        REorFE = REorFE,
        conf.level = conf.level,
        show.study.table = show.study.table)

    analysis <- jmvMetaAnalysisRClass$new(
        options = options,
        data = data)

    analysis$run()

    analysis$results
}
