
# This file is automatically generated, you probably don't want to edit this

jmvMetaAnalysisCohensdOptions <- if (requireNamespace('jmvcore')) R6::R6Class(
    "jmvMetaAnalysisCohensdOptions",
    inherit = jmvcore::Options,
    public = list(
        initialize = function(
            labels = NULL,
            d = NULL,
            n1 = NULL,
            n2 = NULL,
            moderator = NULL,
            correct.for.bias = TRUE,
            REorFE = "RE",
            conf.level = 95,
            show.study.table = FALSE, ...) {

            super$initialize(
                package='esci',
                name='jmvMetaAnalysisCohensd',
                requiresData=TRUE,
                ...)

            private$..labels <- jmvcore::OptionVariable$new(
                "labels",
                labels)
            private$..d <- jmvcore::OptionVariable$new(
                "d",
                d)
            private$..n1 <- jmvcore::OptionVariable$new(
                "n1",
                n1)
            private$..n2 <- jmvcore::OptionVariable$new(
                "n2",
                n2)
            private$..moderator <- jmvcore::OptionVariable$new(
                "moderator",
                moderator)
            private$..correct.for.bias <- jmvcore::OptionBool$new(
                "correct.for.bias",
                correct.for.bias,
                default=TRUE)
            private$..REorFE <- jmvcore::OptionList$new(
                "REorFE",
                REorFE,
                options=list(
                    "RE",
                    "FE"),
                default="RE")
            private$..conf.level <- jmvcore::OptionNumber$new(
                "conf.level",
                conf.level,
                min=50,
                max=99.9999,
                default=95)
            private$..show.study.table <- jmvcore::OptionBool$new(
                "show.study.table",
                show.study.table,
                default=FALSE)

            self$.addOption(private$..labels)
            self$.addOption(private$..d)
            self$.addOption(private$..n1)
            self$.addOption(private$..n2)
            self$.addOption(private$..moderator)
            self$.addOption(private$..correct.for.bias)
            self$.addOption(private$..REorFE)
            self$.addOption(private$..conf.level)
            self$.addOption(private$..show.study.table)
        }),
    active = list(
        labels = function() private$..labels$value,
        d = function() private$..d$value,
        n1 = function() private$..n1$value,
        n2 = function() private$..n2$value,
        moderator = function() private$..moderator$value,
        correct.for.bias = function() private$..correct.for.bias$value,
        REorFE = function() private$..REorFE$value,
        conf.level = function() private$..conf.level$value,
        show.study.table = function() private$..show.study.table$value),
    private = list(
        ..labels = NA,
        ..d = NA,
        ..n1 = NA,
        ..n2 = NA,
        ..moderator = NA,
        ..correct.for.bias = NA,
        ..REorFE = NA,
        ..conf.level = NA,
        ..show.study.table = NA)
)

jmvMetaAnalysisCohensdResults <- if (requireNamespace('jmvcore')) R6::R6Class(
    inherit = jmvcore::Group,
    active = list(
        text = function() private$.items[["text"]],
        result_table = function() private$.items[["result_table"]],
        study_table = function() private$.items[["study_table"]],
        forest_plot = function() private$.items[["forest_plot"]]),
    private = list(),
    public=list(
        initialize=function(options) {
            super$initialize(
                options=options,
                name="",
                title="Meta-Analysis - Cohen d")
            self$add(jmvcore::Html$new(
                options=options,
                name="text",
                title="Instructions/Errros",
                visible=TRUE))
            self$add(jmvcore::Table$new(
                options=options,
                name="result_table",
                title="Meta-Analysis Results",
                visible=TRUE,
                rows=0,
                columns=list(
                    list(
                        `name`="label", 
                        `title`="Label", 
                        `type`="text"))))
            self$add(jmvcore::Table$new(
                options=options,
                name="study_table",
                title="Table of Studies",
                visible=TRUE,
                rows=0,
                columns=list(
                    list(
                        `name`="label", 
                        `title`="Label", 
                        `type`="text"))))
            self$add(jmvcore::Image$new(
                options=options,
                name="forest_plot",
                title="Forest Plot",
                visible=TRUE,
                width=500,
                height=800,
                renderFun=".plot"))}))

jmvMetaAnalysisCohensdBase <- if (requireNamespace('jmvcore')) R6::R6Class(
    "jmvMetaAnalysisCohensdBase",
    inherit = jmvcore::Analysis,
    public = list(
        initialize = function(options, data=NULL, datasetId="", analysisId="", revision=0) {
            super$initialize(
                package = 'esci',
                name = 'jmvMetaAnalysisCohensd',
                version = c(1,0,0),
                options = options,
                results = jmvMetaAnalysisCohensdResults$new(options=options),
                data = data,
                datasetId = datasetId,
                analysisId = analysisId,
                revision = revision,
                pause = NULL,
                completeWhenFilled = FALSE,
                requiresMissings = FALSE)
        }))

#' Meta-Analysis - Cohen d
#'
#' 
#' @param data .
#' @param labels .
#' @param d .
#' @param n1 .
#' @param n2 .
#' @param moderator .
#' @param correct.for.bias .
#' @param REorFE .
#' @param conf.level .
#' @param show.study.table .
#' @return A results object containing:
#' \tabular{llllll}{
#'   \code{results$text} \tab \tab \tab \tab \tab a html \cr
#'   \code{results$result_table} \tab \tab \tab \tab \tab a table \cr
#'   \code{results$study_table} \tab \tab \tab \tab \tab a table \cr
#'   \code{results$forest_plot} \tab \tab \tab \tab \tab an image \cr
#' }
#'
#' Tables can be converted to data frames with \code{asDF} or \code{\link{as.data.frame}}. For example:
#'
#' \code{results$result_table$asDF}
#'
#' \code{as.data.frame(results$result_table)}
#'
#' @export
jmvMetaAnalysisCohensd <- function(
    data,
    labels,
    d,
    n1,
    n2,
    moderator,
    correct.for.bias = TRUE,
    REorFE = "RE",
    conf.level = 95,
    show.study.table = FALSE) {

    if ( ! requireNamespace('jmvcore'))
        stop('jmvMetaAnalysisCohensd requires jmvcore to be installed (restart may be required)')

    if ( ! missing(labels)) labels <- jmvcore::resolveQuo(jmvcore::enquo(labels))
    if ( ! missing(d)) d <- jmvcore::resolveQuo(jmvcore::enquo(d))
    if ( ! missing(n1)) n1 <- jmvcore::resolveQuo(jmvcore::enquo(n1))
    if ( ! missing(n2)) n2 <- jmvcore::resolveQuo(jmvcore::enquo(n2))
    if ( ! missing(moderator)) moderator <- jmvcore::resolveQuo(jmvcore::enquo(moderator))
    if (missing(data))
        data <- jmvcore::marshalData(
            parent.frame(),
            `if`( ! missing(labels), labels, NULL),
            `if`( ! missing(d), d, NULL),
            `if`( ! missing(n1), n1, NULL),
            `if`( ! missing(n2), n2, NULL),
            `if`( ! missing(moderator), moderator, NULL))


    options <- jmvMetaAnalysisCohensdOptions$new(
        labels = labels,
        d = d,
        n1 = n1,
        n2 = n2,
        moderator = moderator,
        correct.for.bias = correct.for.bias,
        REorFE = REorFE,
        conf.level = conf.level,
        show.study.table = show.study.table)

    analysis <- jmvMetaAnalysisCohensdClass$new(
        options = options,
        data = data)

    analysis$run()

    analysis$results
}
